### ISSUE TITLE
 UNIMPLEMENTED: Method not found.

### ISSUE THREAD

**Issue by munkhuushmgl** [googleapis/java-mediatranslation#14]
2. OS type and version: macOs 
3. Java version: 11, 8
4. mediatranslation version(s): 0.1.0

#### Steps to reproduce

  1. Used `java-docs-samples-testing` project
  2. API already enabled
  3. tried using python one still same error
  4. asked product team to whitelist `java-docs-samples-testing' project, and they did it. However still getting the same error.

#### Code example

```java
try (SpeechTranslationServiceClient speechTranslationServiceClient = SpeechTranslationServiceClient.create()) {
      TranslateSpeechConfig translateSpeechConfig = TranslateSpeechConfig.newBuilder()
              .setAudioEncoding("linear16")
              .setSourceLanguageCode("en-US")
              .setTargetLanguageCode("fr-FR")
              .build();

      Path path = Paths.get(filePath);
      byte[] content = Files.readAllBytes(path);
      ByteString audioContent = ByteString.copyFrom(content);
      StreamingTranslateSpeechConfig config = StreamingTranslateSpeechConfig.newBuilder().setAudioConfig(translateSpeechConfig).build();

      BidiStream<StreamingTranslateSpeechRequest, StreamingTranslateSpeechResponse> bidiStream =
              speechTranslationServiceClient.streamingTranslateSpeechCallable().call();

      StreamingTranslateSpeechRequest request = StreamingTranslateSpeechRequest.newBuilder().setAudioContent(audioContent).setStreamingConfig(config).build();
      bidiStream.send(request);

      for (StreamingTranslateSpeechResponse response : bidiStream) { ----> this is throwing the error
```

#### Stack trace
```
Exception in thread "main" com.google.api.gax.rpc.UnimplementedException: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:65)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.ExceptionResponseObserver.onErrorImpl(ExceptionResponseObserver.java:82)
	at com.google.api.gax.rpc.StateCheckingResponseObserver.onError(StateCheckingResponseObserver.java:86)
	at com.google.api.gax.grpc.GrpcDirectStreamController$ResponseObserverAdapter.onClose(GrpcDirectStreamController.java:149)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.RuntimeException: Asynchronous task failed
		at com.google.api.gax.rpc.ServerStreamIterator.hasNext(ServerStreamIterator.java:105)
		at main.examples.MediaTranslateExample.translateFromFile(MediaTranslateExample.java:62)
		at main.examples.MediaTranslateExample.main(MediaTranslateExample.java:40)
Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found.
```

**Comment by chingor13** [comment]
@munkhuushmgl Sorry, missed this issue being filed - the resolution was that the default endpoint is supposed to be prefixed with `us-`?

**Comment by munkhuushmgl** [comment]
Yes that was it!
